baseURL = 'https://bnichols.xyz/'
languageCode = 'en-us'
title = 'bnichols.xyz'
theme = 'charlolamode'

# Customizations for charlolamode theme
menu.main = []

[params.profileMode]
title = 'Welcome!'
description = """\
    My name is Brian. I built this personal site with [Hugo](https://gohugo.io/), \
    deployed with [Terraform](https://www.terraform.io/), \
    and hosted by [Google Cloud Platform](https://cloud.google.com/storage/docs/hosting-static-website). \
    Checkout the source code on [GitHub](https://github.com/briannic/bnichols.xyz). \
"""
buttons = []
imageUrl = '/images/hs.jpeg'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/briannic'

[[params.socialIcons]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/brian-p-nichols/'

[[deployment.targets]]
name = 'bnichols.xyz'
URL = 'gs://bnichols.xyz'
